name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # 当推送版本标签时触发，如 v1.0.0
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows executable
        run: flutter build windows --release

      - name: Archive Windows build
        run: |
          cd build/windows/x64/runner/Release
          7z a -tzip ../../../../../solar_system_simulation-windows.zip ./*

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: solar_system_simulation-windows.zip

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/*.apk

  create-release:
    needs: [build-windows, build-android]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: Download Android artifacts
        uses: actions/download-artifact@v4
        with:
          name: android-build

      - name: Get tag name
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: Solar System Simulation ${{ steps.tag.outputs.tag }}
          body: |
            ## 太阳系模拟器 ${{ steps.tag.outputs.tag }}
            
            ### 下载说明
            - **Windows**: 下载 `solar_system_simulation-windows.zip`，解压后运行 `solar_system_simulation.exe`
            - **Android**: 
              - `app-arm64-v8a-release.apk` - 适用于 64位 ARM 设备（推荐）
              - `app-armeabi-v7a-release.apk` - 适用于 32位 ARM 设备
              - `app-x86_64-release.apk` - 适用于 x86_64 设备
            
            ### 更新内容
            - 请查看提交历史获取详细更新内容
          draft: false
          prerelease: false

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./solar_system_simulation-windows.zip
          asset_name: solar_system_simulation-windows.zip
          asset_content_type: application/zip

      - name: Upload Android ARM64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-arm64-v8a-release.apk
          asset_name: solar_system_simulation-arm64-v8a.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Android ARMv7 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-armeabi-v7a-release.apk
          asset_name: solar_system_simulation-armeabi-v7a.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Android x86_64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-x86_64-release.apk
          asset_name: solar_system_simulation-x86_64.apk
          asset_content_type: application/vnd.android.package-archive
